// Code generated by 'yaegi extract github.com/kf5grd/keybasebot/pkg/util'. DO NOT EDIT.

package main

import (
	"github.com/kf5grd/keybasebot/pkg/util"
	"reflect"
)

func init() {
	Symbols["github.com/kf5grd/keybasebot/pkg/util/util"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ChannelString": reflect.ValueOf(util.ChannelString),
		"HasMinRole":    reflect.ValueOf(util.HasMinRole),
		"StringInSlice": reflect.ValueOf(util.StringInSlice),
	}
}
