// Code generated by 'yaegi extract github.com/kf5grd/keybasebot'. DO NOT EDIT.

package main

import (
	"github.com/kf5grd/keybasebot"
	"reflect"
)

func init() {
	Symbols["github.com/kf5grd/keybasebot/keybasebot"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Adapt":           reflect.ValueOf(keybasebot.Adapt),
		"CommandPrefix":   reflect.ValueOf(keybasebot.CommandPrefix),
		"Contains":        reflect.ValueOf(keybasebot.Contains),
		"FromUser":        reflect.ValueOf(keybasebot.FromUser),
		"FromUsers":       reflect.ValueOf(keybasebot.FromUsers),
		"MessageType":     reflect.ValueOf(keybasebot.MessageType),
		"MinRole":         reflect.ValueOf(keybasebot.MinRole),
		"New":             reflect.ValueOf(keybasebot.New),
		"ReactionTrigger": reflect.ValueOf(keybasebot.ReactionTrigger),

		// type definitions
		"Adapter":    reflect.ValueOf((*keybasebot.Adapter)(nil)),
		"Bot":        reflect.ValueOf((*keybasebot.Bot)(nil)),
		"BotAction":  reflect.ValueOf((*keybasebot.BotAction)(nil)),
		"BotCommand": reflect.ValueOf((*keybasebot.BotCommand)(nil)),
		"JobAction":  reflect.ValueOf((*keybasebot.JobAction)(nil)),
	}
}
